# Site settings
title: Caio Lopes Portfolio
description: A web site about Caio Lopes and what he is up to
#baseurl: "/"
#url: "https://caiolopes.github.io"

# User settings
username: Caio Lopes
user_description: Current full stack developer at Raccoon.ag. 3+ years experience with web and Android development. Nerd who loves hackathons, entrepreneurship, open source, coffee and vim. Interested in machine learning, data visualization, learn new technologies, and solve challenging problems.
user_title: Software Engineer
email: caiodesaloeps@gmail.com
linkedin_username: caiodesalopes
github_username: caiolopes
facebook_username: caiodesalopes

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
